apiVersion: perf.kubestone.xridge.io/v1alpha1
kind: Drill
metadata:
  name: drill-sample
spec:
  args:
    - --benchmark 
    - \benchmarks\benchmark.yml
  podConfig:
    podScheduling:
      nodeSelector:
        kubernetes.io/os: windows
  image:
    name: bwatada/drill:latest
    # pullPolicy: IfNotPresent
    # pullSecret: null
  benchmarksVolume:
    benchmark.yml: |
      ---
      threads: 4
      base: 'https://kubernetes.io'
      iterations: 1
      rampup: 50

      plan:
        - name: Include other file
          include: other.yml

        - name: Fetch kubernetes.io
          request:
            url: /

    other.yml: |
      ---
      - name: Fetch docs
        request:
          url: /docs

  benchmarkFile: benchmark.yml

  options: --stats
  # Enabling log also automatically inserts the command line arg for output, so you don't have to.
  log: 
      filename: drill.log
      enabled: true
      volume:
        name: output-volume
        path: \tmp\
      volumemount:
        name: output-volume
        path: \tmp\
  completions: 1