---
apiVersion: perf.kubestone.xridge.io/v1alpha1
kind: Iperf2
metadata:
  name: iperf2-linux
spec:
  image:
    name: bwatada/iperf2:linux
    pullPolicy: Always

  serverConfiguration:
    # cmdLineArgs: -p 5001
    podLabels:
      iperf-mode: server

    podScheduling:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - store
            topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        kubernetes.io/os: linux
    hostNetwork: false
    
  clientConfiguration:
    cmdLineArgs: -i 1
    podScheduling:
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: iperf-mode
                operator: In
                values:
                - server
            topologyKey: "kubernetes.io/hostname"

  udp: false
  # Iperf2 is set to always output to a timestamped file for each individual test run, so only enable log if 
  # you want to see the .bat file output.
  # filename is hardcoded in the bat file, as iperf_%timestamp%.csv, so no need for filename here.
  log: 
    enabled: true
    volume:
      name: output-volume
      path: /logs/
    volumemount:
      name: output-volume
      path: /logs/
  completions: 1